---
title: "Pathway Definition"
output:
  html_document:
    css: "~/.R/rmd.css"
    self_contained: true
    mathjax: https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_CHTML
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(out.width='100%')
library(pipeR)
library(stringr)
library(tidyverse)
library(wtl)
loadNamespace('cowplot')
ggplot2::theme_set(wtl::theme_wtl())
```

## GSEA MSigDB (Molecular Signatures Database)

- http://software.broadinstitute.org/gsea/msigdb/
- [Downloads (GUI only)](http://software.broadinstitute.org/gsea/downloads.jsp)

### Read gmt

C2 CP (Canonical Pathways)

- [KEGG](http://www.genome.jp/kegg/)
- [Reactome](http://www.reactome.org/)
- [ST (Signal Transduction KE; Science Signaling)](http://stke.sciencemag.org/)
- [SA (SigmaAldrich)](http://www.sigmaaldrich.com/life-science.html)
- [BioCarta](http://www.biocarta.com/)
- [PID: Pathway Interaction Database](https://pid.nci.nih.gov/)
- [NABA](http://matrisome.org/)


```{r read}
read_gmt = function(infile, n=-1L) {
    readLines(infile, n) %>>%
    purrr::map_df(~{
      .row = wtl::split_chr(.x, '\t')
      tibble(name=.row[1], genes=list(.row[c(-1, -2)]))
    }) %>>%
    (setNames(.$genes, .$name))
}

dbdir = '~/Dropbox/cache/gsea'
.template = file.path(dbdir, '%s.v5.2.symbols.gmt')

gmt_h = sprintf(.template, 'h.all') %>>% read_gmt()
names(gmt_h) = names(gmt_h) %>>% str_replace('^HALLMARK_', '')
#gmt_h %>>% map(~str_subset(.x, 'RAS')) %>>% compact()

gmt_c2cp = sprintf(.template, 'c2.cp') %>>% read_gmt()
gmt_c2 = c('SA', 'ST', 'KEGG', 'PID', 'BIOCARTA', 'REACTOME') %>>%
    purrr::set_names() %>>%
    purrr::map(~{
        .pattern = sprintf('^%s_', .x)
        .out = gmt_c2cp[str_detect(names(gmt_c2cp), .pattern)]
        names(.out) = str_replace_all(names(.out), paste0(.pattern, '|_PATHWAY$'), '')
        .out
    })

gmts = c(list(HALLMARK=gmt_h), gmt_c2)
lengths(gmts)

gmts %>>%
    purrr::map_df(~{tibble(ngenes=lengths(.x))}, .id='group') %>>%
    dplyr::filter(group != 'REACTOME') %>>%
    ggplot(aes(ngenes))+geom_histogram(bins=30)+facet_wrap(~group)
```

### CGC

```{r cgc}
repo = '~/git/innanlab'
cgc = file.path(repo, 'cosmic/cancer_gene_census.csv') %>>%
    read_csv() %>>%
    dplyr::transmute(
    symbol= `Gene Symbol`,
    entrez= `Entrez GeneId`,
    role= `Role in Cancer`,
    vartype= `Mutation Types`,
    tissue= `Tissue Type`,
    molgenet= `Molecular Genetics`,
    type_somatic= `Tumour Types(Somatic)`,
    type_germline= `Tumour Types(Germline)`,
    syndrome= `Cancer Syndrome`,
    synonyms= Synonyms) #%>>% (?.)

cgc_drivers = cgc %>>%
    dplyr::select(symbol, role, molgenet) %>>%
    dplyr::filter(!is.na(role)) %>>% (?.)

check_pathways = function(.gmt, .drivers=cgc_drivers) {
    .drivers %>>% purrr::by_row(~{
      .gene = .x$symbol
      .gmt %>>% map_df(~.gene %in% .x)
    }) %>>%
    dplyr::transmute(gene=symbol, .out) %>>%
    tidyr::unnest() %>>%
    tidyr::gather(pathway, included, -gene)
}

plot_included = function(.data, .name, base_size=12) {
    ggplot(.data, aes(pathway, gene))+
    geom_raster(aes(fill=included))+
    scale_fill_manual(values=c(`TRUE`='#333333', `FALSE`='#dddddd'))+
    coord_fixed()+
    labs(title=.name)+
    wtl::theme_wtl(base_size)+
    theme(axis.text.x=element_text(angle=90, hjust=1, vjust=0.5),
    axis.title=element_blank(), axis.ticks=element_blank(),
    legend.position='none')
}

.ldata = gmts %>>% purrr::keep(~length(.x) < 300) %>>% purrr::map(check_pathways)
.lgp = .ldata %>>% purrr::map2(names(.), plot_included, base_size=8)
.pg = cowplot::plot_grid(plotlist=.lgp, nrow=1, rel_widths=c(2,1,1,3,3,4))
.pg
ggsave('gene_pathway.png', .pg, width=16, height=6)

.tidy = .ldata %>>% map_df(~., .id='group')

.summary = .tidy %>>%
    dplyr::group_by(group, gene) %>>%
    dplyr::summarise(included=sum(included)) %>>%
    dplyr::ungroup() %>>% (?.)

.p = .summary %>>%
    ggplot(aes(gene, included))+
    geom_col(aes(fill=group))+
    scale_fill_brewer(type='qual', palette='Paired')+
    wtl::theme_wtl(8)+
    theme(
      panel.grid.major.x=element_blank(),
      axis.text.x=element_text(angle=90, hjust=1, vjust=0.5),
      axis.title=element_blank(), axis.ticks=element_blank(),
      legend.position=c(0.1,0.9), legend.justification=c(0, 1))
.p
ggsave('hist_gene_pathway.png', .p, width=16, height=3)

.summary %>>%
    dplyr::group_by(group) %>>%
    dplyr::summarise(cover= sum(included > 0), max= max(included), sd=sd(included))

.summary %>>%
    dplyr::filter(included > 0) %>>%
    ggplot(aes(included))+
    geom_histogram(bins=30)+
    facet_wrap(~group)

.tidy %>>%
    dplyr::group_by(group, pathway) %>>%
    dplyr::summarise(included=sum(included)) %>>%
    dplyr::ungroup() %>>%
    dplyr::filter(included > 0) %>>%
    ggplot(aes(included))+
    geom_bar()+
    facet_wrap(~group)
```

### Pereira

```{r pereira, eval=FALSE}
pereira_drivers = file.path(repo, 'pereira/drivers40.tsv') %>>% read_tsv() %>>% (?.)

check_pathways_pere = function(.gmt, .drivers=pereira_drivers) {
    .drivers %>>% purrr::by_row(~{
      .gene = .x$gene
      .gmt %>>% map_df(~.gene %in% .x)
    }) %>>%
    dplyr::transmute(gene=paste0(gene, '-', pathway) %>>% factor(., levels=.), .out) %>>%
    tidyr::unnest() %>>%
    tidyr::gather(pathway, included, -gene)
}

.ldata = gmts %>>% purrr::keep(~length(.x) < 300) %>>% purrr::map(check_pathways_pere)
.lgp = .ldata %>>% purrr::map2(names(.), plot_included, base_size=10)
cowplot::plot_grid(plotlist=.lgp)
```


### Bioconductor

https://bioconductor.org/packages/GSEABase

あんまり更新されてないっぽい。

```{r bioc, eval=FALSE}
# source("https://bioconductor.org/biocLite.R")
# biocLite("GSEABase")
library(GSEABase)
gsc = getGmt(infile, SymbolIdentifier(), BroadCollection(category="h"))
groupnames = names(gsc) %>>% str_replace('^[^_]+_', '')

## class GeneSetCollection
showMethods('GeneSetCollection')
geneIds(gsc)

## class GeneSet
showMethods('GeneSet')
gsc[['HALLMARK_P53_PATHWAY']]
details(gsc[['HALLMARK_P53_PATHWAY']])

# フルの情報が欲しい場合はセットごとにまたダウンロードが必要
broad_base = 'http://software.broadinstitute.org/gsea/msigdb/cards'
p53 = asBroadUri('HALLMARK_P53_PATHWAY', base=broad_base) %>>% getBroadSets()
details(p53[[1]])
```
