---
title: "Pathway Definition"
output:
  html_document:
    css: "~/.R/rmd.css"
    self_contained: true
    theme: null
    mathjax: null
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(out.width='100%')
library(stringr)
library(tidyverse)
library(jsonlite)
library(wtl)
loadNamespace('cowplot')
ggplot2::theme_set(wtl::theme_wtl())
```

## GSEA MSigDB (Molecular Signatures Database)

- http://software.broadinstitute.org/gsea/msigdb/
- [Downloads (GUI only)](http://software.broadinstitute.org/gsea/downloads.jsp)

### Read gmt

C2 CP (Canonical Pathways)

- [KEGG](http://www.genome.jp/kegg/)
- [Reactome](http://www.reactome.org/)
- [ST (Signal Transduction KE; Science Signaling)](http://stke.sciencemag.org/)
- [SA (SigmaAldrich)](http://www.sigmaaldrich.com/life-science.html)
- [BioCarta](http://www.biocarta.com/)
- [PID: Pathway Interaction Database](https://pid.nci.nih.gov/)
- [NABA](http://matrisome.org/)


```{r read}
read_gmt = function(infile, n=-1L) {
    readLines(infile, n) %>%
    purrr::map_dfr(~{
      .row = wtl::split_chr(.x, '\t')
      tibble::tibble(name=.row[1], genes=list(.row[c(-1, -2)]))
    }) %>%
    {stats::setNames(.$genes, .$name)}
}

dbdir = '~/Dropbox/cache/gsea'
.template = file.path(dbdir, '%s.v5.2.symbols.gmt')

gmt_h = sprintf(.template, 'h.all') %>% read_gmt()
names(gmt_h) = names(gmt_h) %>% str_replace('^HALLMARK_', '')
#gmt_h %>% map(~str_subset(.x, 'RAS')) %>% compact()

gmt_c2cp = sprintf(.template, 'c2.cp') %>% read_gmt()
gmt_c2 = c('SA', 'ST', 'KEGG', 'PID', 'BIOCARTA') %>%
    purrr::set_names() %>%
    purrr::map(~{
        .pattern = sprintf('^%s_', .x)
        .out = gmt_c2cp[str_detect(names(gmt_c2cp), .pattern)]
        names(.out) = str_replace_all(names(.out), paste0(.pattern, '|_PATHWAY$'), '')
        .out
    })

gmts = c(list(HALLMARK=gmt_h), gmt_c2)
length(gmts)

gmts %>%
    purrr::map_dfr(~{tibble(ngenes=lengths(.x))}, .id='group') %>%
    ggplot(aes(ngenes))+
    geom_histogram(bins=30)+
    facet_wrap(~group)
```

## Other definitions

```{r other-defs}
repo = '~/git/innanlab'
drivers_all = file.path(repo, 'driver_genes.tsv') %>% read_tsv()
pereira_drivers = file.path(repo, 'pereira/drivers40.tsv') %>%
    read_tsv() %>%
    dplyr::rename(symbol=gene) %>% print()
# intersect(pereira_drivers$symbol, tr$primary)
# intersect(pereira_drivers$symbol, tr$synonym)

.tolist = function(.data, .key='pathway', .value='symbol') {
    .data %>%
    dplyr::mutate_(.dots=setNames(list(~str_split(.[[.key]], ':')), 'tmpkey')) %>%
    tidyr::unnest() %>%
    dplyr::distinct(tmpkey, symbol) %>%
    tidyr::drop_na() %>%
    dplyr::group_by(tmpkey) %>%
    dplyr::summarize(genes=list(symbol)) %>%
    {setNames(.$genes, .$tmpkey)}
}

other_defs = list(
  vogelstein= .tolist(drivers_all, 'vogel_pathway'),
  vogelstein3= .tolist(drivers_all, 'vogel_process'),
  pereira= .tolist(pereira_drivers, 'pathway'))
```

## Save

```{r write, eval=FALSE}
pathdefs = c(other_defs, gmts)
pathdefs %>% {all.equal(., fromJSON(toJSON(.)))}
write_json(pathdefs, 'pathway-defs.json')
```


## Check

### Define driver genes

```{r drivers, eval=FALSE}
if (FALSE) {
    .pathdefs = pathdefs
    pathdefs = read_json('pathway-defs.json', simplifyVector=TRUE)
    all.equal(pathdefs, .pathdefs)
}

lengths(pathdefs)

check_pathways = function(.pdef, .drivers=drivers) {
    .drivers %>% purrr::pmap_dfr(function(symbol, ...) {
      .gene = symbol
      .pdef %>% purrr::map_dfr(~{.gene %in% .x})
    }) %>%
    dplyr::transmute(symbol=symbol, .out) %>%
    tidyr::unnest() %>%
    tidyr::gather(pathway, included, -symbol)
}

.tmp_ldata = pathdefs[c('HALLMARK', 'vogelstein', 'vogelstein3', 'pereira')] %>%
    purrr::map(check_pathways, .drivers=drivers_all)

mapped_genes = .tmp_ldata %>%
    purrr::map_dfr(~., .id='group') %>%
    dplyr::group_by(symbol) %>%
    dplyr::summarise(included=sum(included)) %>%
    dplyr::filter(included > 0) %>%
    {.$symbol}

drivers = drivers_all %>% dplyr::filter(symbol %in% mapped_genes)
.ldata = pathdefs %>% purrr::map(check_pathways, .drivers=drivers)
.tidy = .ldata %>% purrr::map_dfr(~., .id='group')
```

### Summary and plot

```{r, eval=FALSE}
plot_included = function(.data, .name, base_size=12) {
    ggplot(.data, aes(pathway, symbol))+
    geom_raster(aes(fill=included))+
    scale_fill_manual(values=c(`TRUE`='#333333', `FALSE`='#dddddd'))+
    coord_fixed()+
    labs(title=.name)+
    wtl::theme_wtl(base_size)+
    theme(axis.text.x=element_text(angle=90, hjust=1, vjust=0.5),
    axis.title=element_blank(), axis.ticks=element_blank(),
    legend.position='none')
}
.lgp = .ldata %>% purrr::map2(names(.), plot_included, base_size=8)
.pg = cowplot::plot_grid(plotlist=.lgp, nrow=1, rel_widths=c(2,1,1,2,1,1,3,3,4))
.pg
ggsave('gene_pathway.png', .pg, width=16, height=12)


.summary = .tidy %>%
    dplyr::group_by(group, symbol) %>%
    dplyr::summarise(included=sum(included)) %>%
    dplyr::ungroup()

.summary %>%
    dplyr::group_by(group) %>%
    dplyr::summarise(cover= sum(included > 0), max= max(included), sd=sd(included))

.summary %>%
    dplyr::filter(included > 0) %>%
    ggplot(aes(included))+
    geom_bar()+
    facet_wrap(~group)

.tidy %>%
    dplyr::group_by(group, pathway) %>%
    dplyr::summarise(ngenes=sum(included)) %>%
    dplyr::ungroup() %>%
    dplyr::filter(ngenes > 0) %>%
    ggplot(aes(ngenes))+
    geom_bar()+
    facet_wrap(~group)

.p = .tidy %>%
    dplyr::group_by(group, symbol) %>%
    dplyr::summarise(included=sum(included)) %>%
    dplyr::ungroup() %>% print() %>%
    ggplot(aes(symbol, included))+
    geom_col(aes(fill=group))+
    scale_fill_brewer(type='qual', palette='Paired')+
    wtl::theme_wtl(8)+
    theme(
      panel.grid.major.x=element_blank(),
      axis.text.x=element_text(angle=90, hjust=1, vjust=0.5),
      axis.title=element_blank(), axis.ticks=element_blank(),
      legend.position=c(0.05,0.95), legend.justification=c(0, 1))
.p
ggsave('hist_gene_pathway.png', .p, width=16, height=5)
```


### Pereira 2016

```{r pereira-genes, eval=FALSE}
check_pathways_pere = function(.pdef, .drivers=pereira_drivers) {
    .drivers %>% purrr::pmap_dfr(function(symbol, ...) {
      .gene = symbol
      .pdef %>% purrr::map_dfr(~{.gene %in% .x})
    }) %>%
    dplyr::transmute(symbol=paste0(symbol, '-', pathway) %>% factor(., levels=.), .out) %>%
    tidyr::unnest() %>%
    tidyr::gather(pathway, included, -symbol)
}

.ldata = pathdefs %>% purrr::keep(~length(.x) < 100) %>% purrr::map(check_pathways_pere)
.lgp = .ldata %>% purrr::map2(names(.), plot_included, base_size=6)
cowplot::plot_grid(plotlist=.lgp, nrow=1, rel_widths=c(2,1,2,5,2,3))
ggsave('pereira_consistency.png', width=14, height=6)
```
